#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

echo "Remember to use 'secret' as password"

keyprefix=$1
private_key="$keyprefix-private.pem"
public_key="$keyprefix-public.pem"

mkdir -p keys
openssl genrsa -des3 -out "keys/$private_key" 2048
openssl rsa -in "keys/$private_key" -outform PEM -pubout -out "keys/$public_key"

echo "Generated 'keys/$private_key' and 'keys/$public_key'"
