#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

echo "Remember to use 'secret' as password"

mkdir -p keys
openssl genrsa -des3 -out keys/private.pem 2048
openssl rsa -in keys/private.pem -outform PEM -pubout -out keys/public.pem

echo "Generated 'keys/private.pem' and 'keys/public.pem'"
